import { motion } from 'framer-motion';
import { ScanSearch, Clock3, Scale, FileWarning, CircleHelp, Eye, BadgeCheck, Upload, Image, ScanLine, Blocks, BookOpenCheck, BrainCircuit, Gauge, FileBarChart, MessageCircle, Wand2, LayoutDashboard, ChartNoAxesCombined, Layers3, GraduationCap, Route, ArrowRight, FileText } from 'lucide-react';
import { Reveal } from '../components/Reveal'; import { SectionTitle } from '../components/SectionTitle';
const problems=[['Teachers can’t evaluate every paper',ScanSearch,'Practice should not be limited by available time.'],['Feedback arrives too late',Clock3,'Learning moments fade while students wait.'],['AI gives inconsistent marks',Scale,'A number without reasoning creates doubt.'],['OCR only extracts text',FileWarning,'It misses context, structure and intent.'],['No one knows why marks were lost',CircleHelp,'Feedback should make the next attempt better.']];
const stages=[['Image Upload',Upload],['Image Validation',Image],['Perspective Correction',ScanLine],['OCR',ScanSearch],['Question Detection',Blocks],['Answer Reconstruction',FileText],['Rubric Retrieval',BookOpenCheck],['GPT-5.6 Evaluation',BrainCircuit],['Confidence Engine',Gauge],['Student Report',FileBarChart]];
const features=[['AI Evaluation',BrainCircuit,'Marks grounded in the question and rubric.'],['Handwriting OCR',ScanLine,'Read real answers, not just clean text.'],['Image Validation',Image,'Catch blur, glare and framing early.'],['Confidence Engine',Gauge,'Show how much to trust each decision.'],['Rubric Checking',BookOpenCheck,'Evaluate against a transparent standard.'],['WhatsApp Ready',MessageCircle,'Meet students where they already are.'],['Actionable Feedback',Wand2,'Turn every result into a next step.']];
const tech=[['Frontend','React + Vite','⚛'],['Backend','FastAPI','⚡'],['Database','Supabase','◆'],['OCR','Tesseract','⌁'],['LLM','GPT-5.6','✦'],['Deployment','Hostinger VPS','◈'],['Messaging','WhatsApp Cloud API','◔'],['Version control','GitHub','⌘']];
const journey=['Receive question paper','Write answers','Upload images','OCR + validation','Evaluation','Feedback','Model answer','Confidence report'];
export function Problem(){return <section id="problem" className="section problem"><SectionTitle eyebrow="01 / THE GAP" title="The problem isn’t grading. It’s trust." copy="Handwritten practice still matters. The feedback loop around it is broken."/><div className="problem-grid">{problems.map(([title,Icon,copy],i)=><Reveal key={title} delay={i*.06}><article className="problem-card"><span className="card-no">0{i+1}</span><Icon/><h3>{title}</h3><p>{copy}</p><span className="card-line"/></article></Reveal>)}</div></section>}
export function Vision(){return <section className="section vision"><Reveal><h2>We’re building<br/><i>trustworthy AI.</i></h2><blockquote>“Trust is more important<br/>than automation.”</blockquote></Reveal><div className="question-grid">{[[CircleHelp,'Can AI understand handwriting?'],[Eye,'Can AI explain every mark?'],[BadgeCheck,'Can AI know when it’s uncertain?']].map(([Icon,text],i)=><Reveal key={text} delay={i*.1}><article><Icon/><span>0{i+1}</span><h3>{text}</h3><ArrowRight size={18}/></article></Reveal>)}</div></section>}
export function Process(){return <section id="process" className="section process"><SectionTitle eyebrow="03 / FROM PAPER TO PROGRESS" title="Every decision has a trail." copy="A multi-stage reasoning pipeline, designed to surface uncertainty instead of hiding it."/><div className="pipeline">{stages.map(([name,Icon],i)=><Reveal key={name} delay={i*.04} className="pipeline-item"><div className="stage-icon"><Icon size={20}/></div><b>{String(i+1).padStart(2,'0')}</b><span>{name}</span>{i<stages.length-1&&<div className="pipe-line"/>}</Reveal>)}</div></section>}
export function Confidence(){const scores=[['Image quality',97],['OCR confidence',91],['Question detection',95],['Evaluation',89]]; return <section id="confidence" className="section confidence"><div className="confidence-intro"><SectionTitle title="Confidence is a feature, not a footnote." copy="We don’t just generate marks. We explain how confident the AI is at every stage."/><div className="confidence-copy"><p>When confidence falls, Paper Checker says so. It can request a better photo or explain where uncertainty entered the result.</p></div></div><div className="confidence-grid"><Reveal className="meter-wrap"><div className="meter"><svg viewBox="0 0 200 200"><defs><linearGradient id="meterGradient"><stop stopColor="#5d72ff"/><stop offset=".55" stopColor="#a266ff"/><stop offset="1" stopColor="#53e6ff"/></linearGradient></defs><circle cx="100" cy="100" r="81"/><motion.circle cx="100" cy="100" r="81" initial={{pathLength:0}} whileInView={{pathLength:.9}} viewport={{once:true}} transition={{duration:1.7}}/></svg><div><span>OVERALL</span><strong>90<small>%</small></strong><b>High confidence</b></div></div><p>AI that knows when it might be wrong.</p></Reveal><div className="score-list">{scores.map(([name,score],i)=><Reveal key={name} delay={i*.12}><article className="score"><div><span>{name}</span><b>{score}%</b></div><div className="bar"><motion.i initial={{width:0}} whileInView={{width:score+'%'}} viewport={{once:true}} transition={{duration:1,delay:i*.12}}/></div></article></Reveal>)}</div></div></section>}
export function Journey(){return <section className="section journey"><SectionTitle eyebrow="05 / STUDENT JOURNEY" title="From a handwritten page to a clear next step."/><div className="journey-line">{journey.map((item,i)=><Reveal className="journey-step" key={item} delay={i*.05}><span>{String(i+1).padStart(2,'0')}</span><i/><h3>{item}</h3></Reveal>)}</div></section>}
export function Features(){return <section className="section features"><SectionTitle eyebrow="06 / BUILT FOR CLARITY" title="A better feedback loop."/><div className="feature-grid">{features.map(([name,Icon,copy],i)=><Reveal key={name} delay={i*.04}><article><div className="feature-icon"><Icon size={22}/></div><h3>{name}</h3><p>{copy}</p><span className="feature-arrow">↗</span></article></Reveal>)}</div></section>}
export function Technology(){return <section id="technology" className="section technology"><SectionTitle eyebrow="07 / THE SYSTEM" title="Modern tools. One focused workflow." copy="A pragmatic stack, composed for a fast and trustworthy experience."/><div className="tech-grid">{tech.map(([k,v,mark],i)=><motion.article key={v} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.05}} whileHover={{y:-6,rotate:i%2?.5:-.5}}><span>{mark}</span><div><small>{k}</small><h3>{v}</h3></div></motion.article>)}</div></section>}
export function Roadmap(){const items=[['Teacher dashboard',LayoutDashboard],['Learning analytics',ChartNoAxesCombined],['Multiple subjects',Layers3],['Multiple boards',GraduationCap],['Adaptive learning',Route],['Personal recommendations',Wand2]];return <section className="section roadmap"><SectionTitle eyebrow="08 / WHAT’S NEXT" title="Designed to grow with every learner."/><div>{items.map(([name,Icon],i)=><Reveal key={name} delay={i*.08}><article><span>{String(i+1).padStart(2,'0')}</span><Icon/><h3>{name}</h3><i/></article></Reveal>)}</div></section>}
